version: "3.9"  # Specify the Compose file version

services:
  neo4j:
    image: neo4j:5.25-enterprise
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/123456789
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/logs:/logs
      - ./neo4j/neo4j.dump:/var/lib/neo4j/import/neo4j.dump
    command: >
      bash -c "
        neo4j-admin database load neo4j --from-path=/var/lib/neo4j/import --overwrite-destination &&
        neo4j-admin dbms set-initial-password 123456789 &&
        neo4j console"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Map the `app/` directory
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=123456789
